/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

/**
 *
 * @author migue_000
 */
public class NaLista extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NaLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.png"))); // NOI18N
        getContentPane().add(jLabel13);
        jLabel13.setBounds(10, 310, 90, 10);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("< VOLTAR");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 10, 120, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/protótipos/pkgfinal/yellow.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 210, 250, 2);

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 0, 0);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("EPISÓDIOS PARA ASSISTIR");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(510, 0, 500, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grey.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 1310, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Doctor_Who_Series_9.png"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 80, 160, 240);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("S10E01");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 320, 60, 20);

        jLabel12.setText("+ 65 episódios");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(60, 320, 80, 20);

        jLabel14.setText("A New Companion");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(10, 340, 120, 14);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(180, 310, 140, 10);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/protótipos/pkgfinal/yellow.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 210, 250, 2);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Doctor_Who_Series_9.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(180, 80, 160, 240);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setText("S02E08");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 320, 60, 20);

        jLabel17.setText("+ 30 episódios");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 320, 80, 20);

        jLabel18.setText("Boom Town");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(180, 340, 120, 14);

        jTextField1.setText("Nome da Série");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 50, 110, 20);

        jButton1.setText("Buscar");
        getContentPane().add(jButton1);
        jButton1.setBounds(130, 50, 73, 23);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Última vez assistida", "Episódios Restando" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(1090, 50, 140, 20);

        jLabel19.setText("Ordenar por:");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(1020, 50, 80, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NaLista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NaLista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
